# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvrnormArma <- function(n, mu, sigma) {
    .Call('KBminmaxpoly_mvrnormArma', PACKAGE = 'KBminmaxpoly', n, mu, sigma)
}

x_fun_cpp <- function(x, grad) {
    .Call('KBminmaxpoly_x_fun_cpp', PACKAGE = 'KBminmaxpoly', x, grad)
}

rep_fun <- function(x, anzahl) {
    .Call('KBminmaxpoly_rep_fun', PACKAGE = 'KBminmaxpoly', x, anzahl)
}

chi_square_fun <- function(n, sigma) {
    .Call('KBminmaxpoly_chi_square_fun', PACKAGE = 'KBminmaxpoly', n, sigma)
}

S_fun_cpp <- function(x, grad, sigmahat, Xinv) {
    .Call('KBminmaxpoly_S_fun_cpp', PACKAGE = 'KBminmaxpoly', x, grad, sigmahat, Xinv)
}

g_fun_cpp <- function(x, grad, T, Xinv) {
    .Call('KBminmaxpoly_g_fun_cpp', PACKAGE = 'KBminmaxpoly', x, grad, T, Xinv)
}

x_fun_prime_cpp <- function(x, grad) {
    .Call('KBminmaxpoly_x_fun_prime_cpp', PACKAGE = 'KBminmaxpoly', x, grad)
}

timesTwo <- function(x) {
    .Call('KBminmaxpoly_timesTwo', PACKAGE = 'KBminmaxpoly', x)
}

