# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

x_fun_cpp <- function(x, grad) {
    .Call('KBminmaxpoly_x_fun_cpp', PACKAGE = 'KBminmaxpoly', x, grad)
}

x_fun_prime_cpp <- function(x, grad) {
    .Call('KBminmaxpoly_x_fun_prime_cpp', PACKAGE = 'KBminmaxpoly', x, grad)
}

g_fun_cpp <- function(x, T_vec, grad, inv_X, x_fun) {
    .Call('KBminmaxpoly_g_fun_cpp', PACKAGE = 'KBminmaxpoly', x, T_vec, grad, inv_X, x_fun)
}

timesTwo <- function(x) {
    .Call('KBminmaxpoly_timesTwo', PACKAGE = 'KBminmaxpoly', x)
}

